# shellcheck shell=bash
# komodo.sh — pure helpers that turn a directory of docker-compose files into a
# Komodo resource-sync TOML (one git-backed Stack per compose file).
#
# Every function here is side-effect-light and dependency-free (coreutils + sed
# only) so it can be sourced and unit-tested in isolation, without spinning up
# just, nix, git or a Komodo instance. The `komodo-sync` recipe sources this via
# {{justfile_directory()}}/lib/.

# Extract "owner/repo" from an https or ssh git remote URL.
# Handles: https://github.com/owner/repo(.git) and git@github.com:owner/repo(.git)
# Usage: komodo_git_slug <remote-url>
komodo_git_slug() {
  local url="${1%.git}"
  # First sed strips an https-style "scheme://host/" prefix; the second strips
  # an ssh-style "user@host:" prefix. Only one applies to any given URL.
  printf '%s\n' "$url" | sed -E 's#^[a-z]+://[^/]+/##; s#^[^@]*@[^:]+:##'
}

# Extract the git host (e.g. github.com) from an https or ssh git remote URL.
# Usage: komodo_git_host <remote-url>
komodo_git_host() {
  local url="${1%.git}"
  printf '%s\n' "$url" | sed -E 's#^[a-z]+://##; s#^[^@]*@##; s#[:/].*$##'
}

# Derive a Komodo stack name from a compose file path: basename without its
# extension (media.yaml -> media).
# Usage: komodo_stack_name <path>
komodo_stack_name() {
  local base
  base=$(basename -- "$1")
  printf '%s\n' "${base%.*}"
}

# Emit the leading comment banner and the self-managing [[resource_sync]] block.
# Usage: komodo_emit_header <sync-name> <host> <account> <repo> <branch> <sync-path>
komodo_emit_header() {
  local name="$1" host="$2" account="$3" repo="$4" branch="$5" path="$6"
  printf '# Generated by `ft komodo-sync` from containers/*.yaml — do not edit by hand.\n'
  printf '# Re-run `ft komodo-sync` after adding or removing a compose file, then commit.\n\n'
  printf '[[resource_sync]]\n'
  printf 'name = "%s"\n' "$name"
  printf '[resource_sync.config]\n'
  printf 'git_provider = "%s"\n' "$host"
  [ -n "$account" ] && printf 'git_account = "%s"\n' "$account"
  printf 'repo = "%s"\n' "$repo"
  printf 'branch = "%s"\n' "$branch"
  printf 'resource_path = ["%s"]\n' "$path"
  # managed = false so the sync never deletes resources it does not define; flip
  # to true once you want removed compose files to also remove their stacks.
  printf 'managed = false\n'
}

# Emit one git-backed [[stack]] block. When env content is non-empty it becomes
# the stack's compose `environment` (a .env body that may reference Komodo
# [[VARIABLE]] / [[SECRET]] values).
# Usage: komodo_emit_stack <name> <server> <host> <account> <repo> <branch> <file-path> <env>
komodo_emit_stack() {
  local name="$1" server="$2" host="$3" account="$4" repo="$5" branch="$6" path="$7" env="$8"
  printf '\n[[stack]]\n'
  printf 'name = "%s"\n' "$name"
  printf 'deploy = true\n'
  printf '[stack.config]\n'
  printf 'server = "%s"\n' "$server"
  printf 'git_provider = "%s"\n' "$host"
  [ -n "$account" ] && printf 'git_account = "%s"\n' "$account"
  printf 'repo = "%s"\n' "$repo"
  printf 'branch = "%s"\n' "$branch"
  printf 'file_paths = ["%s"]\n' "$path"
  if [ -n "$env" ]; then
    printf 'environment = """\n%s\n"""\n' "$env"
  fi
}

# Generate the full sync TOML on stdout from a containers directory. Iterates the
# top-level *.yaml / *.yml compose files (config subdirectories are ignored), in
# sorted order, embedding each compose's sibling "<name>.env" as its environment.
# Usage: komodo_generate <containers-dir> <sync-name> <sync-path> <server> <host> <account> <repo> <branch>
komodo_generate() {
  local dir="$1" sync_name="$2" sync_path="$3" server="$4" host="$5" account="$6" repo="$7" branch="$8"
  komodo_emit_header "$sync_name" "$host" "$account" "$repo" "$branch" "$sync_path"

  local f name envfile env
  # `ls | sort` via glob is already sorted by the shell; guard the nullglob case
  # where a pattern has no matches (the literal pattern is skipped below).
  for f in "$dir"/*.yaml "$dir"/*.yml; do
    [ -f "$f" ] || continue
    name=$(komodo_stack_name "$f")
    envfile="$dir/$name.env"
    env=""
    [ -f "$envfile" ] && env=$(cat -- "$envfile")
    komodo_emit_stack "$name" "$server" "$host" "$account" "$repo" "$branch" "$f" "$env"
  done
}
