{
  pkgs,
  config,
  lib,
  ...
}:

{
  # -------------------------------------------------------------------------
  #  FAST TRACK NIX - HOST CONFIGURATION
  # -------------------------------------------------------------------------
  #
  #  This file defines the unique identity of this specific machine ("strix").
  #
  #  WHERE IS THE REST?
  #  You might notice this file is very short! That is intentional.
  #
  #  1. The Boring Stuff (Bootloader, Timezone, Locale, Nix Settings, StateVersion)
  #     is handled automatically by 'modules/system/core.nix'.
  #     We moved it there so you don't have to copy-paste it for every laptop.
  #
  #  2. The User Stuff (Your account, password, groups)
  #     is handled by 'flake.nix' and 'modules/system/user.nix'.
  #
  #  This file is ONLY for:
  #  - importing the hardware Scan (hardware-configuration.nix)
  #  - Hostname
  #  - Feature Toggles (What does this machine actually DO?)
  # -------------------------------------------------------------------------

  imports = [
    # The Hardware Scan (Generated by NixOS installer)
    # This tells NixOS about your specific drives, CPU, and kernel modules.
    ./hardware-configuration.nix
  ];

  mainuser = "joe"; # This identifies who Home Manager should focus on

  superUsers = [
    "joe"
  ];

  # --- IDENTITY ---
  # The name of this machine on your network.
  networking.hostName = "strix";

  boot.kernelParams = [
    "amdgpu.gttsize=98304" # This allows the GPU to use up to 96GB of your 128GB
  ];

  # -------------------------------------------------------------------------
  #  CAPABILITIES & FEATURES
  # -------------------------------------------------------------------------
  #  Instead of manually installing 50 different packages (steam, drivers, etc),
  #  we use "Feature Flags" to enable bundles of functionality.
  #
  #  How it works:
  #  1. 'enable = true' turns on a module in the 'modules/features' folder.
  #  2. That module installs the packages and sets the config options for you.
  #  3. If you want to disable something, just set it to 'false' (or delete it).
  # -------------------------------------------------------------------------

  # Gaming: Uncomment to enable Steam, Gamemode, Lutris, and MangoHud
  ft.profiles.gaming = {
    enable = true;
    user = "joe"; # Change this to your actual Linux username
    gpuVendor = "amd"; # Set to "amd", "nvidia", or "intel"
    desktopEnvironment = "cosmic";
    enableLeanbackUI = false; # Keeps the normal desktop boot flow
  };

  ft.desktop.cosmic.enable = true; # Enable the Cosmic Desktop Environment

  # Virtualization (Podman): Uncomment to enable containers and Docker compatibility
  # ft.system.podman.enable = true;

  ft.containers.enable = true;

  ft.containers.ai.enable = true;

  ft.system.maintenance.enable = true;
}
