{
  pkgs,
  config,
  lib,
  ...
}:

{
  # -------------------------------------------------------------------------
  #  FAST TRACK NIX - HOST CONFIGURATION
  # -------------------------------------------------------------------------
  #
  #  This file defines the unique identity of this specific machine ("t14").
  #
  #  WHERE IS THE REST?
  #  You might notice this file is very short! That is intentional.
  #
  #  1. The Boring Stuff (Bootloader, Timezone, Locale, Nix Settings, StateVersion)
  #     is handled automatically by 'modules/system/core.nix'.
  #     We moved it there so you don't have to copy-paste it for every laptop.
  #
  #  2. The User Stuff (Your account, password, groups)
  #     is handled by 'flake.nix' and 'modules/system/user.nix'.
  #
  #  This file is ONLY for:
  #  - importing the hardware Scan (hardware-configuration.nix)
  #  - Hostname
  #  - Feature Toggles (What does this machine actually DO?)
  # -------------------------------------------------------------------------

  imports = [
    # The Hardware Scan (Generated by NixOS installer)
    # This tells NixOS about your specific drives, CPU, and kernel modules.
    ./hardware-configuration.nix
  ];

  # --- IDENTITY ---
  # The name of this machine on your network.
  networking.hostName = "t14";

  # -------------------------------------------------------------------------
  #  CAPABILITIES & FEATURES
  # -------------------------------------------------------------------------
  #  Instead of manually installing 50 different packages (steam, drivers, etc),
  #  we use "Feature Flags" to enable bundles of functionality.
  #
  #  How it works:
  #  1. 'enable = true' turns on a module in the 'modules/features' folder.
  #  2. That module installs the packages and sets the config options for you.
  #  3. If you want to disable something, just set it to 'false' (or delete it).
  # -------------------------------------------------------------------------

  # Gaming: Uncomment to enable Steam, Gamemode, Lutris, and MangoHud
  #ft.gaming.enable = true;
  ft.desktop.cosmic.enable = true; # Enable the Cosmic Desktop Environment
  # NVIDIA Drivers: Uncomment to enable proprietary NVIDIA drivers (required for RTX cards)
  #ft.drivers.nvidia.enable = true;

  # Virtualization (Podman): Uncomment to enable containers and Docker compatibility
  #ft.virtualisation.podman.enable = true;
}
